export const RECORD_USERINFO = "RECORD_USERINFO"; 
export const QUIT_LOGIN = "QUIT_LOGIN";
export const GET_MYARTICLELIST = "GET_MYARTICLELIST";
export const SET_MYARTICLEPAGE = "SET_MYARTICLEPAGE";
export const SET_ACTIVEINDEX = "SET_ACTIVEINDEX";